"use client";
import { useState } from 'react';
import Link from '@/components/app-link';
import { Button } from '@/components/ui/button';
import { fmt, Issue, issueLabels } from '@/lib/baseera/engine';
import { label, typeLabels } from '@/lib/baseera/model';
import { useLab } from '../lab-context';
import { NeedData, StepActions, StepHead } from '../components';
export default function QualityPage() {
  const { sheet, profile } = useLab(), [kind, setKind] = useState<Issue['kind']>('missing'), [page, setPage] = useState(0);
  if (!sheet || !profile) return <NeedData/>;
  const issues = profile.issues.filter(i => i.kind === kind), pages = Math.max(1, Math.ceil(issues.length / 30)), activePage = Math.min(page, pages - 1);
  return <><StepHead eyebrow="DATA HEALTH" title="افهم المشكلة قبل أن تصلحها." text="هذه أعداد فعلية من الورقة الحالية. القيم السالبة والمتطرفة تنبيهات للمراجعة؛ لا تُحذف تلقائيًا، ولا نعطي ملفك درجة جودة وهمية."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Object.entries(issueLabels).map(([key, title]) => <button key={key} className={`quality-card ${kind === key ? 'active' : ''}`} onClick={() => { setKind(key as Issue['kind']); setPage(0); }}><span>{title}</span><strong>{fmt(profile.counts[key as Issue['kind']])}</strong><small>{key === 'duplicate' ? 'صف إضافي مطابق' : 'خلية'} · عرض التفاصيل</small></button>)}</div><section className="surface mt-5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{issueLabels[kind]}</h2><Button asChild size="sm"><Link href="/lab/clean">معاينة التنظيف</Link></Button></div><div className="data-scroll mt-4"><table className="data-grid"><thead><tr><th>معرّف الصف</th><th>العمود</th><th>القيمة</th><th>الملاحظة</th></tr></thead><tbody>{issues.slice(activePage * 30, (activePage + 1) * 30).map((issue, i) => <tr key={i}><td dir="ltr">{issue.rowId}</td><td>{sheet.columns.find(c => c.id === issue.columnId)?.name ?? 'كل الأعمدة'}</td><td dir="auto">{label(issue.value)}</td><td className="whitespace-normal min-w-64 text-sm text-slate-400">{issue.note}</td></tr>)}</tbody></table>{!issues.length && <p className="p-8 text-center text-cyan-200">لا توجد حالات من هذا النوع.</p>}</div><div className="mt-4 flex items-center justify-between"><Button variant="outline" disabled={!activePage} onClick={() => setPage(activePage - 1)}>السابق</Button><span className="text-sm">{activePage + 1} / {pages}</span><Button variant="outline" disabled={activePage + 1 >= pages} onClick={() => setPage(activePage + 1)}>التالي</Button></div></section><section className="surface mt-5 p-5"><h2 className="mb-4 text-xl font-bold">ملخص الأعمدة</h2><div className="data-scroll"><table className="data-grid"><thead><tr>{['العمود', 'النوع', 'فارغ', 'غير صالح', 'قيم مميزة', 'أدنى', 'وسيط', 'أعلى'].map(t => <th key={t}>{t}</th>)}</tr></thead><tbody>{profile.summaries.map(s => <tr key={s.column.id}><td>{s.column.name}</td><td>{typeLabels[s.column.type]}</td><td>{s.missing}</td><td>{s.invalid}</td><td>{s.distinct}</td><td>{fmt(s.min)}</td><td>{fmt(s.median)}</td><td>{fmt(s.max)}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm text-slate-400">الأعداد المميزة تستثني الخلايا الفارغة. إحصاءات الأرقام تستبعد القيم غير الصالحة. كشف التطرف يستخدم 1.5 × IQR.</p></section><StepActions prev="/lab/profile" next="/lab/clean" nextLabel="اختر قرارات التنظيف"/></>;
}
