"use client";
import Image from "next/image";
import {ArrowLeft,BarChart3,BrainCircuit,CheckCircle2,FileSpreadsheet,SearchCheck,ShieldCheck,Sparkles} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Brand} from "./lab/lab-shell";

export default function Home(){return <main dir="rtl" className="min-h-screen overflow-hidden bg-[#050b18] text-white"><header className="border-b border-white/8 bg-[#050b18]/88 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><div className="flex items-center gap-3"><Brand/><div><b className="text-lg">بصيرة <span className="text-cyan-300">| Baseera</span></b><p className="text-[11px] text-slate-500">Analytics Lab</p></div></div><Button asChild className="bg-blue-600 font-bold hover:bg-blue-500"><a href="/lab">ابدأ التحليل<ArrowLeft className="mr-2 h-4 w-4"/></a></Button></div></header>
<section className="relative"><div className="ambient ambient-one"/><div className="mx-auto grid min-h-[720px] max-w-7xl items-center gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[.9fr_1.1fr]"><div className="relative z-10"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/6 px-3 py-1.5 text-sm text-cyan-200"><Sparkles className="h-4 w-4"/>من ملف مربك إلى قرار مفهوم</span><h1 className="mt-6 text-5xl font-black leading-[1.15] tracking-tight sm:text-7xl">بياناتك فيها قصة.<br/><span className="text-gradient">بصيرة تساعدك تشوفها.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">أنا أسيد، مهندس ذكاء اصطناعي ومدرب. أحب أفهم البيانات، لكن بصراحة ما بحب أضيع بين خلايا Excel ومعادلاته. من هون بدأت فكرة بصيرة.</p><p className="mt-3 max-w-xl leading-7 text-slate-500">مساحة تسألك قبل أن تحسب، وتريك أثر قراراتك، وتساعدك تصل إلى نتيجة تستطيع شرحها والتحقق منها.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-13 bg-blue-600 px-6 text-base font-bold hover:bg-blue-500"><a href="/lab">خلّيني أفهم ملفي<ArrowLeft className="mr-2 h-5 w-5"/></a></Button><Button asChild variant="outline" className="h-13 border-cyan-400/25 bg-cyan-400/5 px-6 text-base text-cyan-100 hover:bg-cyan-400/10 hover:text-white"><a href="/lab?demo=1">جرّب بملف جاهز<FileSpreadsheet className="mr-2 h-5 w-5"/></a></Button></div></div><div className="relative"><div className="story-frame"><Image src="/baseera-story.png" alt="رحلة من ملف بيانات معقد إلى لوحة تحليل واضحة" width={1536} height={1024} priority className="h-auto w-full object-cover"/><div className="story-caption"><span>الفوضى</span><i/><span>الفهم</span><i/><span>القرار</span></div></div></div></div></section>
<section className="border-y border-white/7 bg-[#071020]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="eyebrow">لماذا بصيرة؟</p><h2 className="text-3xl font-black sm:text-5xl">المشكلة لم تكن في الأرقام.<br/>المشكلة كانت: من أين أبدأ؟</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3"><StoryCard number="01" icon={FileSpreadsheet} title="ملف لا أعرفه" text="أعمدة كثيرة، قيم ناقصة، وصيغ لا أعرف إن كانت صحيحة."/><StoryCard number="02" icon={BrainCircuit} title="سؤال بلغة بسيطة" text="ماذا أريد أن أعرف؟ وما الذي أستطيع إثباته من الملف فعلًا؟"/><StoryCard number="03" icon={BarChart3} title="قرار أستطيع الدفاع عنه" text="نتيجة واضحة، قيد معلن، وخطوة تالية يمكن اختبارها."/></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid items-start gap-12 lg:grid-cols-[.65fr_1.35fr]"><div className="lg:sticky lg:top-8"><p className="eyebrow">كيف تعمل؟</p><h2 className="text-3xl font-black leading-tight sm:text-5xl">رحلة واحدة.<br/>كل صفحة تجيب عن سؤال.</h2><p className="mt-5 leading-7 text-slate-500">بصيرة لا ترمي كل الأدوات أمامك. تأخذك خطوة بخطوة وتحفظ قراراتك خلال الرحلة.</p></div><div className="grid gap-3 sm:grid-cols-2">{[[SearchCheck,"افهم وافحص","ما الموجود في الملف؟ وما المشاكل التي قد تغيّر النتيجة؟"],[CheckCircle2,"نظّف بقرارك","شاهد أثر كل قرار قبل اعتماده."],[BarChart3,"حلّل وصمّم","اختر المؤشر، المقارنة، الرسم، والفلتر."],[ShieldCheck,"تحقّق ثم قرّر","راجع الحساب والادعاء قبل مشاركة التقرير."]].map(([Icon,title,text],i)=>{const C=Icon as typeof SearchCheck;return <div className="how-card" key={String(title)}><span>0{i+1}</span><C className="h-6 w-6 text-cyan-300"/><h3>{String(title)}</h3><p>{String(text)}</p></div>})}</div></div></section>
<section className="px-5 pb-20 sm:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-[28px] border border-cyan-300/15 bg-gradient-to-l from-blue-600/15 to-cyan-300/5 p-8 text-center sm:p-14"><p className="eyebrow">جاهز تشوف القصة داخل ملفك؟</p><h2 className="text-3xl font-black sm:text-5xl">ابدأ بسؤال واحد… ودع بصيرة ترتّب الرحلة.</h2><Button asChild className="mt-7 h-13 bg-cyan-300 px-7 text-base font-black text-slate-950 hover:bg-cyan-200"><a href="/lab">ابدأ تحليل ملفك<ArrowLeft className="mr-2 h-5 w-5"/></a></Button></div></section><footer className="border-t border-white/7 py-7 text-center text-sm text-slate-600">بصيرة | Baseera Analytics · فكرة وتطوير Osaid Alhawamdeh</footer></main>}
function StoryCard({number,icon:Icon,title,text}:{number:string;icon:typeof FileSpreadsheet;title:string;text:string}){return <div className="story-card"><div className="flex items-center justify-between"><Icon className="h-7 w-7 text-cyan-300"/><span>{number}</span></div><h3>{title}</h3><p>{text}</p></div>}
