"use client";
import { useRef, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { AnalysisResult, aggregateLabels, fmt, operationLabels } from '@/lib/baseera/engine';
import { ChartKind, makeSheet, Sheet } from '@/lib/baseera/model';
import { downloadBlob, exportCsv, safeName } from '@/lib/baseera/io';
const colors = ['#38bdf8', '#376cff', '#2dd4bf', '#a78bfa', '#fbbf24', '#fb7185'];
export function AnalysisView({ result, sheet, chart, onChartChange, compact = false }: { result: AnalysisResult; sheet: Sheet; chart: ChartKind; onChartChange?: (v: ChartKind) => void; compact?: boolean }) {
  const [page, setPage] = useState(0), graph = useRef<HTMLDivElement>(null);
  const plan = result.plan, metric = sheet.columns.find(c => c.id === plan.metric)?.name ?? '', dimension = sheet.columns.find(c => c.id === plan.dimension)?.name ?? '';
  const overall = plan.operation === 'correlation' ? result.correlation : plan.operation === 'distribution' ? result.summary.median : plan.aggregation === 'count' ? result.rows : result.valid ? result.summary[plan.aggregation] : null;
  const overallLabel = plan.operation === 'correlation' ? 'معامل Pearson' : plan.operation === 'distribution' ? 'وسيط القيم' : `${aggregateLabels[plan.aggregation]} الكلي`;
  const scatter = plan.operation === 'correlation', plot = result.points.slice(0, scatter ? 2000 : 24), pages = Math.max(1, Math.ceil(result.points.length / 30)), activePage = Math.min(page, pages - 1);
  const allowed: ChartKind[] = scatter ? ['scatter', 'table'] : plan.operation === 'distribution' ? ['bar', 'table'] : plan.operation === 'trend' ? ['line', 'area', 'bar', 'table'] : ['bar', 'pie', 'table'];
  const kind = allowed.includes(chart) ? chart : allowed[0], nonnegative = result.points.every(p => p.value !== null && p.value >= 0), pieAllowed = nonnegative && result.points.length <= 12 && result.points.some(p => (p.value ?? 0) > 0) && ['sum', 'count'].includes(plan.aggregation);
  const table = kind === 'table' || kind === 'pie' && !pieAllowed;
  const tooltip = <Tooltip contentStyle={{ background: '#0b1931', border: '1px solid #365374', borderRadius: 10, color: '#e2e8f0' }} labelStyle={{ color: '#e2e8f0' }} formatter={(v) => fmt(Number(v))}/>;
  const axes = <><CartesianGrid stroke="#233044" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{ fill: '#a8b8cc', fontSize: 12 }} tickLine={false} axisLine={false} minTickGap={20}/><YAxis width={72} tick={{ fill: '#a8b8cc', fontSize: 12 }} tickFormatter={v => fmt(v)} axisLine={false} tickLine={false}/>{tooltip}</>;
  return <div className="analysis-result"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{plan.title}</h2><p className="mt-2 text-sm text-slate-400">{operationLabels[plan.operation]} · {plan.operation === 'correlation' ? `${dimension} × ${metric}` : plan.operation === 'distribution' ? metric : `${aggregateLabels[plan.aggregation]}${plan.aggregation === 'count' ? '' : ` ${metric}`} حسب ${dimension}`}</p></div>{onChartChange && <label className="field-label">شكل العرض<select aria-label="شكل الرسم" className="field" value={kind} onChange={e => onChartChange(e.target.value as ChartKind)}>{allowed.map(c => <option key={c} value={c}>{{ bar: 'أعمدة', line: 'خطي', area: 'مساحي', pie: 'دائري', scatter: 'نقاط', table: 'جدول' }[c]}</option>)}</select></label>}</div>
    {!compact && <div className="metric-strip my-5"><div><span>صفوف بعد الفلتر</span><strong>{fmt(result.rows)}</strong></div><div><span>ساهمت في الحساب</span><strong>{fmt(result.valid)}</strong></div><div><span>لم تساهم</span><strong>{fmt(result.skipped)}</strong></div><div><span>{overallLabel}</span><strong>{fmt(overall)}</strong></div></div>}
    {compact && <p className="mt-3 text-sm text-cyan-200">{overallLabel}: <b dir="ltr">{fmt(overall)}</b> · {result.valid} صف مساهم</p>}
    {result.skipped > 0 && <p className="notice my-3 text-sm">{result.skipped} صف لم يساهم بسبب قيمة رقمية أو تاريخ غير صالح/فارغ. راجع الجودة قبل اعتماد الاستنتاج.</p>}
    {kind === 'pie' && !pieAllowed && <p className="notice my-3 text-sm">الرسم الدائري يحتاج مجموعًا أو عددًا، وقيمًا غير سالبة، و12 فئة كحد أقصى. استخدم الأعمدة للمقارنة.</p>}
    {!table && result.points.length > 0 && <><div ref={graph} className="result-chart" dir="ltr"><ResponsiveContainer width="100%" height="100%">{kind === 'scatter' ? <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 10 }}><CartesianGrid stroke="#233044" strokeDasharray="3 3"/><XAxis type="number" dataKey="x" name={dimension} tick={{ fill: '#a8b8cc', fontSize: 12 }}/><YAxis type="number" dataKey="y" name={metric} tick={{ fill: '#a8b8cc', fontSize: 12 }}/>{tooltip}<Scatter data={plot} fill="#38bdf8" isAnimationActive={false}/></ScatterChart> : kind === 'pie' ? <PieChart>{tooltip}<Pie data={plot} dataKey="value" nameKey="name" outerRadius="75%" label={({ name }) => name} isAnimationActive={false}>{plot.map((_, i) => <Cell key={i} fill={colors[i % colors.length]}/>)}</Pie></PieChart> : kind === 'line' ? <LineChart data={plot} margin={{ top: 20, right: 20, bottom: 15, left: 0 }}>{axes}<Line type="linear" dataKey="value" name={metric || 'القيمة'} stroke="#38bdf8" strokeWidth={3} dot={{ r: 4 }} connectNulls={false} isAnimationActive={false}/></LineChart> : kind === 'area' ? <AreaChart data={plot} margin={{ top: 20, right: 20, bottom: 15, left: 0 }}>{axes}<Area type="linear" dataKey="value" name={metric || 'القيمة'} stroke="#38bdf8" fill="#38bdf8" fillOpacity={.14} connectNulls={false} isAnimationActive={false}/></AreaChart> : <BarChart data={plot} margin={{ top: 20, right: 20, bottom: 15, left: 0 }}>{axes}<Bar dataKey="value" name={plan.operation === 'distribution' || plan.aggregation === 'count' ? 'عدد الصفوف' : metric} fill="#376cff" radius={[5, 5, 0, 0]} isAnimationActive={false}/></BarChart>}</ResponsiveContainer></div>{plot.length < result.points.length && <p className="text-sm text-amber-200">الرسم يعرض أول {plot.length} من {result.points.length} {scatter ? 'نقطة بترتيب الملف' : 'مجموعة'}. الحساب والجدول والتصدير تشمل النتيجة كاملة.</p>}</>}
    {!result.points.length && <p className="py-16 text-center text-slate-400">لا توجد نتائج تطابق الخطة. راجع الفلاتر وأنواع الأعمدة.</p>}
    {scatter && <p className="my-3 text-sm text-slate-400">Pearson محسوب على كل الأزواج الصالحة. الارتباط لا يثبت السببية؛ ويكون غير معرّف عند ثبات أحد العمودين أو قلة الأزواج.</p>}
    {plan.operation === 'distribution' && <p className="my-3 text-sm text-slate-400">كل فئة تشمل حدها الأدنى وتستثني الأعلى، عدا الأخيرة فتشمله. العناوين مقربة للعرض؛ إسناد القيم يستخدم الحدود الدقيقة.</p>}
    {!compact && <><details open={table} className="mt-4"><summary className="cursor-pointer text-sm font-bold text-cyan-200">جدول النتائج الكامل · {result.points.length} {scatter ? 'زوجًا' : 'مجموعة'}</summary><div className="data-scroll mt-3"><table className="data-grid"><thead><tr><th>{scatter ? dimension : plan.operation === 'distribution' ? 'الفئة الرقمية' : dimension}</th><th>{scatter ? metric : 'القيمة'}</th><th>الصفوف</th><th>المساهمة</th></tr></thead><tbody>{result.points.slice(activePage * 30, (activePage + 1) * 30).map((p, i) => <tr key={i}><td>{scatter ? fmt(p.x) : p.name}</td><td>{fmt(p.value)}</td><td>{p.rows}</td><td>{p.valid}</td></tr>)}</tbody></table></div><div className="mt-3 flex items-center justify-between"><Button variant="outline" size="sm" disabled={!activePage} onClick={() => setPage(activePage - 1)}>السابق</Button><span className="text-xs">{activePage + 1} / {pages}</span><Button variant="outline" size="sm" disabled={activePage + 1 >= pages} onClick={() => setPage(activePage + 1)}>التالي</Button></div></details><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => exportCsv(makeSheet(plan.title, [['group_or_x', 'value_or_y', 'rows', 'valid'], ...result.points.map(p => [scatter ? p.x ?? null : p.name, p.value, p.rows, p.valid])], 0))}>تصدير النتائج CSV</Button>{!table && !!result.points.length && <Button variant="outline" size="sm" onClick={() => { const svg = graph.current?.querySelector('svg'); if (!svg) return; const clone = svg.cloneNode(true) as SVGElement; clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); clone.setAttribute('style', 'background:#081224;font-family:Arial,sans-serif'); downloadBlob(new Blob([new XMLSerializer().serializeToString(clone)], { type: 'image/svg+xml' }), safeName(plan.title) + '.svg'); }}>تنزيل الرسم SVG</Button>}</div></>}
    {compact && table && <div className="data-scroll mt-4"><table className="data-grid"><tbody>{result.points.slice(0, 12).map((p, i) => <tr key={i}><td>{scatter ? fmt(p.x) : p.name}</td><td>{fmt(p.value)}</td></tr>)}</tbody></table>{result.points.length > 12 && <p className="text-xs text-slate-400 mt-2">أول 12 نتيجة؛ افتح التحليل لعرض الكل.</p>}</div>}
  </div>;
}
