"use client";
import {createContext,useCallback,useContext,useEffect,useMemo,useState} from "react";
import {demoRows,numberValue,parseCsv,Policies,Row,stableRow,valueLabel} from "./data";

type Analysis={sum:number;count:number;average:number;chart:{name:string;value:number;rows:number}[]};
type LabValue={hydrated:boolean;fileName:string;rawRows:Row[];columns:string[];numericColumns:string[];categoryColumns:string[];quality:{missing:number;duplicates:number;negatives:number;textNeedsTrim:number};policies:Policies;setPolicy:(key:keyof Policies,value:boolean)=>void;cleanedRows:Row[];metric:string;setMetric:(v:string)=>void;dimension:string;setDimension:(v:string)=>void;analysis:Analysis;score:number;verified:boolean;setVerified:(v:boolean)=>void;loadDemo:()=>void;loadFile:(file:File)=>Promise<void>;reset:()=>void};
const LabContext=createContext<LabValue|null>(null);
const defaults:Policies={removeDuplicates:true,quarantineNegative:true,trimText:true,convertNumbers:true};

export function LabProvider({children}:{children:React.ReactNode}){
 const[hydrated,setHydrated]=useState(false),[fileName,setFileName]=useState(""),[rawRows,setRawRows]=useState<Row[]>([]),[policies,setPolicies]=useState(defaults),[metric,setMetric]=useState(""),[dimension,setDimension]=useState(""),[verified,setVerified]=useState(false);
 useEffect(()=>{try{const saved=sessionStorage.getItem("baseera-session");if(saved){const x=JSON.parse(saved);setFileName(x.fileName??"");setRawRows(x.rawRows??[]);setPolicies(x.policies??defaults);setMetric(x.metric??"");setDimension(x.dimension??"");setVerified(!!x.verified)}}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(hydrated)sessionStorage.setItem("baseera-session",JSON.stringify({fileName,rawRows,policies,metric,dimension,verified}))},[hydrated,fileName,rawRows,policies,metric,dimension,verified]);
 const columns=useMemo(()=>rawRows.length?Object.keys(rawRows[0]):[],[rawRows]);
 const numericColumns=useMemo(()=>columns.filter(c=>{const vals=rawRows.map(r=>r[c]).filter(v=>v!==null&&v!=="");return vals.length>0&&vals.filter(v=>numberValue(v)!==null).length/vals.length>=.6}),[columns,rawRows]);
 const categoryColumns=useMemo(()=>columns.filter(c=>!numericColumns.includes(c)),[columns,numericColumns]);
 useEffect(()=>{if(numericColumns.length&&!numericColumns.includes(metric))setMetric(numericColumns.at(-1)??"");if(categoryColumns.length&&!categoryColumns.includes(dimension))setDimension(categoryColumns.find(c=>/region|منطقة|product|منتج/i.test(c))??categoryColumns[0])},[numericColumns,categoryColumns,metric,dimension]);
 const quality=useMemo(()=>{const missing=rawRows.reduce((s,r)=>s+columns.filter(c=>r[c]===null||r[c]==="").length,0);const seen=new Set<string>();let duplicates=0,negatives=0;rawRows.forEach(r=>{const k=stableRow(r,columns);if(seen.has(k))duplicates++;else seen.add(k);negatives+=columns.filter(c=>(numberValue(r[c])??0)<0).length});const textNeedsTrim=rawRows.reduce((s,r)=>s+columns.filter(c=>typeof r[c]==="string"&&r[c]!==String(r[c]).trim()).length,0);return{missing,duplicates,negatives,textNeedsTrim}},[rawRows,columns]);
 const cleanedRows=useMemo(()=>{let rows=rawRows.map(r=>Object.fromEntries(columns.map(c=>{let v=r[c];if(policies.trimText&&typeof v==="string")v=v.trim();if(policies.convertNumbers&&numericColumns.includes(c))v=numberValue(v);return[c,v]})) as Row);if(policies.removeDuplicates){const seen=new Set<string>();rows=rows.filter(r=>{const k=stableRow(r,columns);if(seen.has(k))return false;seen.add(k);return true})}if(policies.quarantineNegative)rows=rows.filter(r=>!numericColumns.some(c=>(numberValue(r[c])??0)<0));return rows},[rawRows,columns,policies,numericColumns]);
 const analysis=useMemo(()=>{if(!metric)return{sum:0,count:0,average:0,chart:[]};const vals=cleanedRows.map(r=>numberValue(r[metric])).filter((v):v is number=>v!==null),sum=vals.reduce((a,b)=>a+b,0),grouped=new Map<string,{value:number;rows:number}>();cleanedRows.forEach(r=>{const name=valueLabel(r[dimension]),cur=grouped.get(name)??{value:0,rows:0};grouped.set(name,{value:cur.value+(numberValue(r[metric])??0),rows:cur.rows+1})});return{sum,count:vals.length,average:vals.length?sum/vals.length:0,chart:[...grouped.entries()].map(([name,v])=>({name,...v})).sort((a,b)=>b.value-a.value).slice(0,10)}},[cleanedRows,metric,dimension]);
 const score=useMemo(()=>{let v=100;if(quality.missing)v-=Math.min(20,quality.missing*2);if(!policies.removeDuplicates&&quality.duplicates)v-=20;if(!policies.quarantineNegative&&quality.negatives)v-=25;if(!policies.trimText&&quality.textNeedsTrim)v-=10;return Math.max(35,v)},[quality,policies]);
 const load=(rows:Row[],name:string)=>{const clean=rows.filter(r=>Object.values(r).some(v=>v!==null&&v!==""));if(!clean.length)throw new Error("لم أجد صفوف بيانات داخل الملف");setRawRows(clean);setFileName(name);setPolicies(defaults);setVerified(false);sessionStorage.setItem("baseera-session",JSON.stringify({fileName:name,rawRows:clean,policies:defaults,metric:"",dimension:"",verified:false}))};
 const loadDemo=useCallback(()=>load(demoRows,"Demo_Sales.csv"),[]);
 const loadFile=async(file:File)=>{const ext=file.name.split(".").pop()?.toLowerCase();if(ext==="csv")load(parseCsv(await file.text()),file.name);else if(ext==="xlsx"||ext==="xls"){const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{cellDates:true}),sheet=wb.Sheets[wb.SheetNames[0]];load(XLSX.utils.sheet_to_json<Row>(sheet,{defval:null,raw:true}),file.name)}else throw new Error("ارفع ملف CSV أو Excel بصيغة XLSX أو XLS")};
 const reset=()=>{setFileName("");setRawRows([]);setPolicies(defaults);setMetric("");setDimension("");setVerified(false);sessionStorage.removeItem("baseera-session")};
 const setPolicy=(key:keyof Policies,value:boolean)=>{setPolicies(p=>({...p,[key]:value}));setVerified(false)};
 useEffect(()=>{const context=typeof document==="undefined"?undefined:(document as Document&{modelContext?:{registerTool?:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController(),register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool?.(tool,{signal:lifecycle.signal})).catch(()=>undefined)}catch{}};register({name:"load_baseera_demo",title:"بدء تجربة بصيرة",description:"يحمّل ملف المبيعات التعليمي ويبدأ رحلة التحليل المرئية.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async()=>{loadDemo();return{file:"Demo_Sales.csv",rows:demoRows.length}}});register({name:"configure_cleaning_policy",title:"ضبط سياسة التنظيف",description:"يحدّث قرارات التكرار والقيم السالبة والمسافات في جلسة بصيرة الحالية.",inputSchema:{type:"object",properties:{removeDuplicates:{type:"boolean"},quarantineNegative:{type:"boolean"},trimText:{type:"boolean"}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const x=input as Partial<Policies>;setPolicies(p=>({...p,...x}));setVerified(false);return{updated:true}}});register({name:"read_baseera_summary",title:"قراءة ملخص بصيرة",description:"يعيد حالة التحليل والمؤشرات ودرجة الجاهزية من الجلسة الحالية.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async()=>({file:fileName,rawRows:rawRows.length,acceptedRows:cleanedRows.length,metric,dimension,sum:analysis.sum,average:analysis.average,qualityScore:score,verified})});return()=>lifecycle.abort()},[loadDemo,fileName,rawRows.length,cleanedRows.length,metric,dimension,analysis.sum,analysis.average,score,verified]);
 return <LabContext.Provider value={{hydrated,fileName,rawRows,columns,numericColumns,categoryColumns,quality,policies,setPolicy,cleanedRows,metric,setMetric,dimension,setDimension,analysis,score,verified,setVerified,loadDemo,loadFile,reset}}>{children}</LabContext.Provider>
}
export function useLab(){const x=useContext(LabContext);if(!x)throw new Error("useLab must be used inside LabProvider");return x}
