"use client";
import Link from '@/components/app-link';
import { usePathname } from 'next/navigation';
import { BarChart3, Database, FileCheck2, FileSpreadsheet, Filter, FolderOpen, Home, SearchCheck, ShieldCheck, Sparkles, CloudUpload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLab } from './lab-context';
import { DownloadTray } from './download-tray';
const steps = [['/lab', FileSpreadsheet, 'ابدأ بملف'], ['/lab/profile', Database, 'مساحة البيانات'], ['/lab/quality', SearchCheck, 'جودة البيانات'], ['/lab/clean', Filter, 'التنظيف'], ['/lab/analyze', Sparkles, 'مختبر التحليل'], ['/lab/dashboard', BarChart3, 'لوحة المؤشرات'], ['/lab/verify', ShieldCheck, 'التحقق'], ['/lab/report', FileCheck2, 'التقرير'], ['/lab/projects', FolderOpen, 'مشاريعي']] as const;
export function LabShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(), { project, sheet, switchSheet, notice, setNotice, draftState, saveCloud, saving, cloudState } = useLab();
  return <main dir="rtl" className="baseera-workspace min-h-screen bg-[#050b18] text-slate-100"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#050b18]/95 backdrop-blur-xl"><div className="mx-auto flex min-h-18 max-w-[1800px] items-center justify-between gap-3 px-4 py-3 sm:px-7"><Link href="/" className="flex shrink-0 items-center gap-3"><Brand/><div><b>بصيرة <span className="text-cyan-300">| Baseera</span></b><p className="text-xs text-slate-400">Analytics Workspace</p></div></Link><div className="flex items-center gap-2"><span className="hidden max-w-64 truncate text-sm text-slate-400 md:block">{project?.name}</span><Button asChild variant="ghost"><Link href="/"><Home size={16}/><span className="hidden sm:inline">الرئيسية</span></Link></Button></div></div></header>
    <div className="mx-auto grid max-w-[1800px] gap-5 px-4 py-5 lg:grid-cols-[220px_minmax(0,1fr)] lg:px-7"><aside className="lg:sticky lg:top-23 lg:h-[calc(100vh-108px)]"><div className="overflow-x-auto rounded-2xl border border-white/10 bg-[#081224] p-2 lg:h-full lg:p-3"><p className="hidden px-3 py-3 text-xs tracking-widest text-slate-500 lg:block">من الملف إلى القرار</p><nav aria-label="مراحل التحليل" className="flex min-w-max gap-1 lg:block lg:min-w-0 lg:space-y-1">{steps.map(([href, Icon, title]) => <Link key={href} href={href} className={`journey-link ${path === href ? 'current' : ''}`} aria-current={path === href ? 'page' : undefined}><span className="journey-icon"><Icon size={17}/></span>{title}</Link>)}</nav><div className="mt-4 hidden border-t border-white/10 p-3 text-sm text-slate-400 lg:block"><p>الأرقام تُحسب من بياناتك.</p><p className="mt-2 text-xs leading-6">أنت تختار التعديلات وتراجع أثرها قبل تطبيقها.</p></div></div></aside>
    <section className="min-w-0">{project && <div className="workspace-topbar"><label className="flex items-center gap-2 text-sm">الورقة<select aria-label="الورقة النشطة" className="field max-w-52" value={sheet?.id} onChange={e => switchSheet(e.target.value)}>{project.sheets.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><span className="text-xs text-slate-400">إصدار البيانات {project.revision} · {draftState}</span><div className="flex flex-wrap items-center gap-2 lg:mr-auto"><Button variant="outline" size="sm" disabled={saving} onClick={saveCloud}><CloudUpload size={16}/>{saving ? 'جارٍ الحفظ…' : 'حفظ المشروع'}</Button><span className="max-w-80 text-xs text-slate-400" role="status">{cloudState}</span></div></div>}{notice && <div className="notice mb-4 flex items-start justify-between gap-3" role="status">{notice}<button aria-label="إغلاق التنبيه" onClick={() => setNotice('')}>×</button></div>}{children}</section></div><DownloadTray/></main>;
}
export function Brand() { return <span className="brand-mark" aria-hidden="true"><i/></span>; }
