"use client";
import {usePathname} from "next/navigation";
import {BarChart3,Check,Database,FileCheck2,FileSpreadsheet,Filter,Home,LockKeyhole,SearchCheck,ShieldCheck,Sparkles} from "lucide-react";
import {Button} from "@/components/ui/button";
import {useLab} from "./lab-context";
const steps=[
 ["/lab",FileSpreadsheet,"ارفع الملف"],["/lab/profile",Database,"افهم الملف"],["/lab/quality",SearchCheck,"افحص الجودة"],["/lab/clean",Filter,"نظّف"],["/lab/analyze",Sparkles,"حلّل"],["/lab/dashboard",BarChart3,"صمّم"],["/lab/verify",ShieldCheck,"تحقّق"],["/lab/report",FileCheck2,"قرّر"],
] as const;
export function LabShell({children}:{children:React.ReactNode}){const path=usePathname(),{fileName,rawRows}=useLab(),active=Math.max(0,steps.findIndex(([href])=>href===path));return <main dir="rtl" className="min-h-screen bg-[#050b18] text-slate-100"><header className="sticky top-0 z-50 border-b border-white/8 bg-[#050b18]/92 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-[1600px] items-center justify-between px-4 sm:px-7"><a href="/" className="flex items-center gap-3"><Brand/><div><b>بصيرة <span className="text-cyan-300">| Baseera</span></b><p className="text-[11px] text-slate-500">Analytics Lab</p></div></a><div className="flex items-center gap-2">{fileName&&<span className="hidden rounded-full border border-cyan-400/20 bg-cyan-400/5 px-3 py-1.5 text-xs text-cyan-100 sm:block">{fileName}</span>}<Button asChild variant="ghost" size="sm" className="text-slate-400 hover:bg-white/5 hover:text-white"><a href="/"><Home className="ml-2 h-4 w-4"/>الرئيسية</a></Button></div></div></header><div className="mx-auto grid max-w-[1600px] gap-5 px-4 py-5 lg:grid-cols-[235px_minmax(0,1fr)] lg:px-7"><aside className="lg:sticky lg:top-23 lg:h-[calc(100vh-108px)]"><div className="overflow-x-auto rounded-2xl border border-white/8 bg-[#081224] p-2 lg:h-full lg:overflow-visible lg:p-3"><div className="flex min-w-max gap-1 lg:block lg:min-w-0 lg:space-y-1"><p className="hidden px-3 pb-3 pt-2 text-xs font-bold uppercase tracking-[.16em] text-slate-600 lg:block">رحلة التحليل</p>{steps.map(([href,Icon,label],i)=>{const done=!!rawRows.length&&i<active,current=i===active,locked=!rawRows.length&&i>0;return <a key={href} href={href} title={locked?"افتح المرحلة ثم ارفع ملفًا أو استخدم المثال":""} className={`journey-link ${current?"current":""} ${done?"done":""} ${locked?"locked":""}`}><span className="journey-icon"><Icon className="h-4 w-4"/></span><span>{label}</span>{done?<Check className="mr-auto hidden h-3.5 w-3.5 text-cyan-300 lg:block"/>:locked?<LockKeyhole className="mr-auto hidden h-3 w-3 lg:block"/>:null}</a>})}</div><div className="mt-4 hidden border-t border-white/7 p-3 lg:block"><div className="mb-2 flex justify-between text-xs text-slate-500"><span>التقدم</span><span>{Math.round((active+1)/steps.length*100)}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/6"><div className="h-full rounded-full bg-gradient-to-l from-blue-600 to-cyan-300 transition-all" style={{width:`${(active+1)/steps.length*100}%`}}/></div></div></div></aside><section className="min-w-0">{children}</section></div></main>}
export function Brand(){return <span className="brand-mark" aria-hidden="true"><i/></span>}
