"use client";
import { useMemo, useState } from 'react';
import { ArrowDownToLine, Columns3, Plus, Redo2, Search, Trash2, Undo2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Cell, ColumnType, DataFilter, isoDate, label, numberValue, Sheet, typeLabels, types } from '@/lib/baseera/model';
import { uuid } from '@/lib/baseera/model';
import { exportCsv, exportExcel, saveProjectFile } from '@/lib/baseera/io';
import { filterLabels, matches } from '@/lib/baseera/engine';
import { useLab } from '../lab-context';
import { NeedData, StepActions, StepHead } from '../components';
export default function ProfilePage() { const { sheet } = useLab(); return sheet ? <Workspace key={sheet.id} sheet={sheet}/> : <NeedData/>; }
function Workspace({ sheet }: { sheet: Sheet }) {
  const { project, updateSheet, undo, redo, canUndo, canRedo, setNotice } = useLab();
  const [search, setSearch] = useState(''), [original, setOriginal] = useState(false), [hidden, setHidden] = useState<string[]>([]), [pinned, setPinned] = useState('');
  const [sort, setSort] = useState({ column: '', desc: false }), [page, setPage] = useState(0), [size, setSize] = useState(50), [selected, setSelected] = useState<string[]>([]);
  const [filter, setFilter] = useState<DataFilter>({ column: '', operator: 'contains', value: '' }), [edit, setEdit] = useState<{ row: string; column: string; value: string } | null>(null), [error, setError] = useState('');
  const [columnId, setColumnId] = useState(sheet.columns[0].id), [columnName, setColumnName] = useState(sheet.columns[0].name), [columnType, setColumnType] = useState<ColumnType>(sheet.columns[0].type);
  const columns = original ? sheet.originalColumns : sheet.columns;
  const visible = columns.filter(c => !hidden.includes(c.id)).sort((a, b) => a.id === pinned ? -1 : b.id === pinned ? 1 : 0);
  const rows = useMemo(() => {
    const data = (original ? sheet.originalRows : sheet.rows).filter(r => !r.excluded && (!search || columns.some(c => String(r.values[c.id] ?? '').toLocaleLowerCase().includes(search.toLocaleLowerCase()))) && (!filter.column || matches(r, filter)));
    if (sort.column) { const col = columns.find(c => c.id === sort.column); data.sort((a, b) => { const av = a.values[sort.column], bv = b.values[sort.column], an = numberValue(av), bn = numberValue(bv); const cmp = col?.type === 'number' ? an === null ? bn === null ? 0 : 1 : bn === null ? -1 : an - bn : String(av ?? '').localeCompare(String(bv ?? ''), 'ar', { numeric: true }); return sort.desc ? -cmp : cmp; }); }
    return data;
  }, [sheet, original, search, columns, filter, sort]);
  const pages = Math.max(1, Math.ceil(rows.length / size)), safePage = Math.min(page, pages - 1), displayed = rows.slice(safePage * size, (safePage + 1) * size);
  const act = (fn: () => void) => { try { fn(); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تنفيذ التعديل.'); } };
  const applyCell = () => {
    if (!edit) return;
    act(() => { const column = sheet.columns.find(c => c.id === edit.column)!; let value: Cell = edit.value === '' ? null : edit.value;
      if (value !== null && column.type === 'number') { value = numberValue(value); if (value === null) throw new Error('اكتب رقمًا صالحًا أو اترك الخلية فارغة.'); }
      if (value !== null && column.type === 'date') { const parsed = isoDate(value); if (!parsed) throw new Error('استخدم تنسيق YYYY-MM-DD أو عدّل نوع العمود.'); value = parsed; }
      const previous = sheet.rows.find(r => r.id === edit.row)?.values[edit.column];
      if (previous !== value) updateSheet({ ...sheet, rows: sheet.rows.map(r => r.id === edit.row ? { ...r, values: { ...r.values, [edit.column]: value } } : r) }, `تعديل ${column.name} · ${edit.row}`, 1);
      setEdit(null);
    });
  };
  return <><StepHead eyebrow="DATA WORKSPACE" title="ملفك كاملًا، بين إيديك." text="اضغط أي خلية لتعديلها. ابحث في جميع الصفوف، أو قارن نسخة العمل بالأصل. التصفية هنا للعرض؛ فلاتر التحليل تضبطها داخل المختبر."/>
    <div className="flex flex-wrap items-center gap-2 mb-4"><Button variant="outline" disabled={!canUndo || original} onClick={() => { setEdit(null); undo(); }}><Undo2 size={16}/>تراجع</Button><Button variant="outline" disabled={!canRedo || original} onClick={() => { setEdit(null); redo(); }}><Redo2 size={16}/>إعادة</Button><Button variant="outline" onClick={() => exportCsv({ ...sheet, columns, rows: original ? sheet.originalRows : sheet.rows })}><ArrowDownToLine size={16}/>CSV</Button><Button variant="outline" onClick={() => void exportExcel(project!).catch(e => setError(e.message))}>Excel لكل الأوراق</Button><Button variant="outline" onClick={() => act(() => saveProjectFile(project!))}>نسخة مشروع</Button><select aria-label="نسخة البيانات" className="field w-auto mr-auto" value={original ? 'original' : 'working'} onChange={e => { setOriginal(e.target.value === 'original'); setEdit(null); setSelected([]); setPage(0); }}><option value="working">نسخة العمل · قابلة للتعديل</option><option value="original">الملف الأصلي · للقراءة</option></select></div>
    <div className="surface overflow-hidden"><div className="grid gap-3 border-b border-white/10 p-4 md:grid-cols-2 xl:grid-cols-4"><label className="field-label"><span><Search size={15} className="inline ml-1"/>بحث في جميع الخلايا</span><input className="field" value={search} placeholder="ابحث عن قيمة…" onChange={e => { setSearch(e.target.value); setPage(0); }}/></label><label className="field-label">عمود التصفية<select className="field" value={filter.column} onChange={e => { setFilter({ ...filter, column: e.target.value }); setPage(0); }}><option value="">بدون تصفية</option>{columns.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field-label">المقارنة<select className="field" value={filter.operator} onChange={e => { setFilter({ ...filter, operator: e.target.value as DataFilter['operator'] }); setPage(0); }}>{Object.entries(filterLabels).map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select></label><label className="field-label">القيمة<input className="field" disabled={['empty', 'not_empty'].includes(filter.operator)} value={filter.value} onChange={e => { setFilter({ ...filter, value: e.target.value }); setPage(0); }}/></label></div>
      <details className="border-b border-white/10 p-4"><summary className="cursor-pointer text-sm font-bold text-cyan-200"><Columns3 size={16} className="inline ml-2"/>الأعمدة: عرض، تثبيت، اسم ونوع</summary><div className="mt-4 flex flex-wrap gap-4">{columns.map(c => <label key={c.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!hidden.includes(c.id)} disabled={!hidden.includes(c.id) && visible.length === 1} onChange={e => setHidden(e.target.checked ? hidden.filter(id => id !== c.id) : [...hidden, c.id])}/>{c.name}</label>)}</div><div className="mt-4 grid items-end gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="field-label">ثبّت عمودًا<select className="field" value={pinned} onChange={e => setPinned(e.target.value)}><option value="">بدون تثبيت</option>{visible.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field-label">تعديل العمود<select className="field" value={columnId} onChange={e => { const c = sheet.columns.find(c => c.id === e.target.value)!; setColumnId(c.id); setColumnName(c.name); setColumnType(c.type); }}>{sheet.columns.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field-label">اسم العمود<input className="field" value={columnName} onChange={e => setColumnName(e.target.value)}/></label><label className="field-label">نوع العمود<select className="field" value={columnType} onChange={e => setColumnType(e.target.value as ColumnType)}>{types.map(t => <option key={t} value={t}>{typeLabels[t]}</option>)}</select></label><Button disabled={original} onClick={() => act(() => { const name = columnName.trim(); if (!name || sheet.columns.some(c => c.id !== columnId && c.name === name)) throw new Error('اسم العمود فارغ أو مكرر.'); updateSheet({ ...sheet, columns: sheet.columns.map(c => c.id === columnId ? { ...c, name, type: columnType } : c) }, `تحديث العمود ${name} (${typeLabels[columnType]})`, 0); setNotice('تم تحديث تعريف العمود. تغيير النوع لا يغيّر القيم؛ راجع الجودة أو استخدم التنظيف للتحويل.'); })}>حفظ العمود</Button></div><p className="mt-3 text-xs text-slate-400">الأنواع اقتراح أولي. اختر «معرّف» للأكواد وأرقام الهواتف للحفاظ على الأصفار الافتتاحية.</p></details>
      <div className="flex flex-wrap items-center gap-3 px-4 py-3"><b className="text-sm">{rows.length.toLocaleString('en-US')} صف مطابق من {(original ? sheet.originalRows : sheet.rows).length.toLocaleString('en-US')}</b><span className="text-xs text-slate-400">{visible.length} / {columns.length} أعمدة</span><div className="mr-auto flex gap-2"><Button variant="outline" size="sm" disabled={original} onClick={() => act(() => { updateSheet({ ...sheet, rows: [...sheet.rows, { id: uuid(), values: Object.fromEntries(sheet.columns.map(c => [c.id, null])) }] }, 'إضافة صف', 1); setSearch(''); setFilter({ ...filter, column: '' }); setSort({ column: '', desc: false }); setPage(Math.floor(sheet.rows.length / size)); })}><Plus size={15}/>صف</Button><Button variant="outline" size="sm" disabled={original || !selected.length} onClick={() => { if (window.confirm(`حذف ${selected.length} صف محدد من نسخة العمل؟ يمكنك التراجع.`)) act(() => { updateSheet({ ...sheet, rows: sheet.rows.filter(r => !selected.includes(r.id)) }, 'حذف صفوف محددة', selected.length); setSelected([]); }); }}><Trash2 size={15}/>حذف {selected.length || ''}</Button></div></div>
      {error && <p className="error-box mx-4 mb-3" role="alert">{error}</p>}{edit && <div className="notice mx-4 mb-3 flex flex-wrap items-center gap-2"><span className="text-sm">تعديل {sheet.columns.find(c => c.id === edit.column)?.name} · {edit.row}</span><input autoFocus aria-label="قيمة الخلية" className="field max-w-sm" value={edit.value} onChange={e => setEdit({ ...edit, value: e.target.value })} onKeyDown={e => { if (e.key === 'Enter') applyCell(); if (e.key === 'Escape') setEdit(null); }}/><Button onClick={applyCell}>حفظ الخلية</Button><Button variant="ghost" onClick={() => setEdit(null)}>إلغاء</Button></div>}
      <div className="data-scroll" tabIndex={0} aria-label="جدول البيانات — اسحب أفقيًا لرؤية كل الأعمدة"><table className="data-grid"><thead><tr><th className="w-12"><input aria-label="تحديد صفوف الصفحة" type="checkbox" disabled={original || !displayed.length} checked={!!displayed.length && displayed.every(r => selected.includes(r.id))} onChange={e => setSelected(e.target.checked ? [...new Set([...selected, ...displayed.map(r => r.id)])] : selected.filter(id => !displayed.some(r => r.id === id)))}/></th><th>#</th>{visible.map(c => <th key={c.id} className={pinned === c.id ? 'pinned-col' : ''}><button onClick={() => { setSort({ column: c.id, desc: sort.column === c.id && !sort.desc }); setPage(0); }} title="اضغط للترتيب"><span dir="auto">{c.name}</span> {sort.column === c.id ? sort.desc ? '↓' : '↑' : '↕'}<small className="block mt-1 font-normal text-slate-500">{typeLabels[c.type]}</small></button></th>)}</tr></thead><tbody>{displayed.map((r, i) => <tr key={r.id} className={selected.includes(r.id) ? 'selected-row' : ''}><td><input aria-label={`تحديد الصف ${r.id}`} type="checkbox" disabled={original} checked={selected.includes(r.id)} onChange={e => setSelected(e.target.checked ? [...selected, r.id] : selected.filter(id => id !== r.id))}/></td><td className="text-xs text-slate-500" title={r.id}>{safePage * size + i + 1}</td>{visible.map(c => <td key={c.id} className={pinned === c.id ? 'pinned-col' : ''}>{original ? <span dir="auto">{label(r.values[c.id])}</span> : <button className="cell-value" dir="auto" title={`${c.name}: ${label(r.values[c.id])} — تعديل`} aria-label={`تعديل ${c.name} صف ${r.id}`} onClick={() => { setError(''); setEdit({ row: r.id, column: c.id, value: r.values[c.id] == null ? '' : String(r.values[c.id]) }); }}>{label(r.values[c.id])}</button>}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="p-12 text-center text-slate-400">لا توجد صفوف تطابق البحث أو التصفية.</p>}</div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 p-4 text-sm"><span>عرض {rows.length ? safePage * size + 1 : 0}–{Math.min((safePage + 1) * size, rows.length)} من {rows.length}</span><label className="flex items-center gap-2">صفوف الصفحة<select aria-label="عدد صفوف الصفحة" className="field w-auto" value={size} onChange={e => { setSize(Number(e.target.value)); setPage(0); }}>{[25, 50, 100, 250].map(n => <option key={n}>{n}</option>)}</select></label><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={!safePage} onClick={() => setPage(safePage - 1)}>السابق</Button><label className="flex items-center gap-2">صفحة<input className="field w-20" type="number" min={1} max={pages} value={safePage + 1} onChange={e => setPage(Math.max(0, Math.min(pages - 1, Number(e.target.value) - 1)))}/><span>من {pages}</span></label><Button variant="outline" size="sm" disabled={safePage >= pages - 1} onClick={() => setPage(safePage + 1)}>التالي</Button></div></div>
    </div><details className="surface mt-5 p-5"><summary className="cursor-pointer font-bold">سجل التعديلات ({project!.history.length})</summary><p className="my-3 text-sm text-slate-400">التراجع متاح لآخر التعديلات في هذه الجلسة. الأصل يبقى داخل نسخة المشروع.</p>{project!.history.slice().reverse().slice(0, 50).map(h => <div key={h.id} className="flex flex-wrap justify-between gap-2 border-t border-white/10 py-3 text-sm"><span>{h.label} · {h.affected} متأثر</span><time className="text-xs text-slate-400">{new Date(h.at).toLocaleString('ar-JO')}</time></div>)}{!project!.history.length && <p className="text-slate-400">لم تُجرَ تعديلات بعد.</p>}</details><StepActions prev="/lab" next="/lab/quality" nextLabel="راجع جودة الملف"/>
  </>;
}
