"use client";
import {useMemo,useState} from "react";
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Filter,RotateCcw} from "lucide-react";
import {Button} from "@/components/ui/button";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {StepActions,StepHead,NeedData} from "../components";
import {useLab} from "../lab-context";
import {fmt,numberValue,valueLabel} from "../data";
export default function Dashboard(){const{rawRows,cleanedRows,metric,dimension,analysis}=useLab(),[filter,setFilter]=useState("__all");const options=useMemo(()=>[...new Set(cleanedRows.map(r=>valueLabel(r[dimension])))],[cleanedRows,dimension]);const filtered=useMemo(()=>filter==="__all"?cleanedRows:cleanedRows.filter(r=>valueLabel(r[dimension])===filter),[cleanedRows,dimension,filter]);const values=filtered.map(r=>numberValue(r[metric])).filter((v):v is number=>v!==null),sum=values.reduce((a,b)=>a+b,0),avg=values.length?sum/values.length:0;const chart=filter==="__all"?analysis.chart:[{name:filter,value:sum,rows:filtered.length}];if(!rawRows.length)return <NeedData/>;return <div><StepHead eyebrow="06 · لوحة القرار" title="الفلتر يغيّر نطاق السؤال" text="اختبر اللوحة بنفسك. كل بطاقة يجب أن تتغير لأنها تقرأ من الصفوف نفسها."/><div className="dashboard surface p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Dashboard Preview</p><h2 className="text-xl font-black">لوحة {metric} حسب {dimension}</h2></div><label className="field-label min-w-[220px]"><span className="flex items-center gap-2"><Filter className="h-4 w-4"/>فلتر {dimension}</span><NativeSelect value={filter} onChange={e=>setFilter(e.target.value)}><NativeSelectOption value="__all">كل البيانات</NativeSelectOption>{options.map(o=><NativeSelectOption key={o} value={o}>{o}</NativeSelectOption>)}</NativeSelect></label></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><DashKpi label="إجمالي المؤشر" value={fmt.format(sum)}/><DashKpi label="عدد الصفوف" value={fmt.format(filtered.length)}/><DashKpi label="متوسط القيمة" value={fmt.format(avg)}/></div><div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_.5fr]"><div className="chart-panel h-[330px] p-4" dir="ltr"><ResponsiveContainer><BarChart data={chart}><CartesianGrid vertical={false} stroke="#ffffff12"/><XAxis dataKey="name" tick={{fill:'#94a3b8',fontSize:12}} axisLine={false}/><YAxis tick={{fill:'#64748b',fontSize:11}} axisLine={false} width={48}/><Tooltip contentStyle={{background:'#0b1730',border:'1px solid #ffffff1a',borderRadius:12,color:'#fff'}}/><Bar dataKey="value" fill="#55dfff" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div><div className="chart-panel p-5"><p className="text-sm font-bold">ماذا تغيّر؟</p><div className="mt-4 text-4xl font-black text-cyan-300">{filter==="__all"?"الكل":filter}</div><p className="mt-3 text-sm leading-6 text-slate-500">النطاق الحالي يحتوي {filtered.length} من {cleanedRows.length} صفوف معتمدة.</p>{filter!=="__all"&&<Button variant="outline" onClick={()=>setFilter("__all")} className="mt-5 w-full border-white/10 bg-white/5"><RotateCcw className="ml-2 h-4 w-4"/>إعادة الضبط</Button>}</div></div></div><StepActions prev="/lab/analyze" next="/lab/verify" nextLabel="اختبر النتيجة"/></div>}
function DashKpi({label,value}:{label:string;value:string}){return <div className="dash-kpi"><span>{label}</span><b>{value}</b></div>}

