"use client";
import Link from '@/components/app-link';
import { navigate } from '@/lib/baseera/navigation';
import { ArrowDown, ArrowUp, Plus, Printer, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { analyze } from '@/lib/baseera/engine';
import { useLab } from '../lab-context';
import { NeedData, StepActions, StepHead } from '../components';
import { AnalysisView } from '../analysis-view';
export default function DashboardPage() {
  const { project, updateProject } = useLab(); if (!project) return <NeedData/>;
  const move = (i: number, direction: number) => updateProject(p => { const cards = [...p.cards]; [cards[i], cards[i + direction]] = [cards[i + direction], cards[i]]; return { ...p, cards }; });
  return <><StepHead eyebrow="YOUR DECISION BOARD" title="لوحة تجمع الأسئلة المهمة." text="أضف تحليلات متعددة من أوراق مختلفة. كل بطاقة تُحسب مجددًا من نسخة العمل الحالية؛ وتوضح مصدرها وإصدار البيانات."/><div className="mb-5 flex gap-3"><Button asChild><Link href="/lab/analyze"><Plus size={16}/>تحليل جديد</Link></Button><Button variant="outline" disabled={!project.cards.length} onClick={() => window.print()}><Printer size={16}/>طباعة اللوحة / PDF</Button></div><div className="dashboard-print"><h2 className="print-heading">بصيرة · {project.name}</h2><div className="grid gap-5 xl:grid-cols-2">{project.cards.map((card, i) => {
    const sheet = project.sheets.find(s => s.id === card.sheetId); let result = null, error = ''; try { if (!sheet) throw new Error('ورقة المصدر غير موجودة.'); result = analyze(sheet, card.plan); } catch (e) { error = e instanceof Error ? e.message : 'تعذر حساب البطاقة.'; }
    return <section className="surface dashboard-card p-5" key={card.id}><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-400">{sheet?.name} · الإصدار الحالي {project.revision}{card.createdRevision !== project.revision ? ' · أُعيد الحساب بعد التعديلات' : ''}</p><div className="flex gap-1 no-print"><Button size="icon-sm" variant="ghost" aria-label={`رفع البطاقة ${i + 1}`} disabled={!i} onClick={() => move(i, -1)}><ArrowUp size={14}/></Button><Button size="icon-sm" variant="ghost" aria-label={`خفض البطاقة ${i + 1}`} disabled={i === project.cards.length - 1} onClick={() => move(i, 1)}><ArrowDown size={14}/></Button><Button size="icon-sm" variant="ghost" aria-label={`حذف البطاقة ${i + 1}`} onClick={() => updateProject(p => ({ ...p, cards: p.cards.filter(c => c.id !== card.id) }))}><Trash2 size={14}/></Button></div></div>{error ? <p className="error-box">{error}</p> : result && sheet && <AnalysisView result={result} sheet={sheet} chart={card.chart} onChartChange={chart => updateProject(p => ({ ...p, cards: p.cards.map(c => c.id === card.id ? { ...c, chart } : c) }))} compact/>}<Button className="mt-4 no-print" size="sm" variant="outline" onClick={() => { updateProject(p => ({ ...p, activeSheetId: card.sheetId, activePlan: card.plan, verifiedRevision: null })); void navigate('/lab/analyze').catch(() => {}); }}>فتح النتيجة والتفاصيل</Button></section>;
  })}</div>{!project.cards.length && <div className="surface py-20 text-center"><h2 className="text-2xl font-bold">أول بطاقة تبدأ بسؤال.</h2><p className="mt-3 text-slate-400">نفّذ تحليلًا، ثم اضغط «أضف النتيجة إلى لوحة المؤشرات».</p></div>}</div><StepActions prev="/lab/analyze" next="/lab/verify" nextLabel="راجع النتائج"/></>;
}
