"use client";
import { useState } from 'react';
import { CheckCircle2, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { verification } from '@/lib/baseera/engine';
import { useLab } from '../lab-context';
import { NeedData, StepActions, StepHead } from '../components';
export default function VerifyPage() {
  const { sheet, project, result, updateProject } = useLab(), [acknowledged, setAcknowledged] = useState(false); if (!sheet || !project) return <NeedData/>;
  const checks = verification(sheet, result), passed = checks.every(c => c.pass), current = project.verifiedRevision === project.revision;
  return <><StepHead eyebrow="TRUST THE PROCESS" title="كل نتيجة تحتاج دليلًا." text="هذه فحوص آلية محددة، وليست شهادة بصحة القرار. أي تعديل في البيانات أو خطة التحليل يلغي حالة المراجعة السابقة."/><div className="grid gap-4 md:grid-cols-2">{checks.map(check => <div key={check.name} className="surface flex items-start gap-3 p-5">{check.pass ? <CheckCircle2 className="mt-1 shrink-0 text-emerald-300" size={23}/> : <AlertTriangle className="mt-1 shrink-0 text-amber-300" size={23}/>}<div><h2 className="font-bold">{check.name}</h2><p className="mt-2 text-sm leading-7 text-slate-400">{check.detail}</p><p className={`mt-2 text-xs ${check.pass ? 'text-emerald-300' : 'text-amber-300'}`}>{check.pass ? 'اجتاز الفحص' : 'يحتاج مراجعة'}</p></div></div>)}</div><div className="surface mt-5 p-6"><h2 className="text-xl font-bold">المراجعة البشرية</h2><ul className="my-4 list-disc space-y-2 pr-5 leading-7 text-slate-300"><li>هل اخترت وحدة المقياس والفترة والفلاتر بشكل صحيح؟</li><li>هل القيم الناقصة والتكرار والمرتجعات مفهومة في سياق الملف؟</li><li>هل تجنّبت استنتاج السببية أو الربحية من مقارنة وصفية؟</li></ul><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={acknowledged} onChange={e => setAcknowledged(e.target.checked)}/>راجعت تعريف المقاييس وسياق البيانات وحدود الاستنتاج.</label><Button className="mt-5" disabled={!passed || !acknowledged || current} onClick={() => updateProject(p => ({ ...p, verifiedRevision: p.revision }))}>{current ? 'سُجّلت المراجعة لهذا الإصدار' : 'تسجيل المراجعة'}</Button>{!passed && <p className="mt-3 text-sm text-amber-200">عالج الفحوص غير المجتازة أولًا، أو صدّر التقرير مع إظهار هذه القيود.</p>}</div><StepActions prev="/lab/dashboard" next="/lab/report" nextLabel="اكتب خلاصة القرار"/></>;
}
