"use client";
import {useMemo} from "react";
import {AlertTriangle,CheckCircle2,Play,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Progress} from "@/components/ui/progress";
import {StepActions,StepHead,NeedData} from "../components";
import {useLab} from "../lab-context";
export default function Verify(){const{rawRows,cleanedRows,analysis,quality,policies,verified,setVerified}=useLab();const checks=useMemo(()=>[{label:"مجموع الرسم يطابق المؤشر",ok:analysis.chart.reduce((s,x)=>s+x.value,0)===analysis.sum},{label:"عدد الصفوف المعتمدة موثّق",ok:cleanedRows.length<=rawRows.length},{label:"التكرارات عولجت أو وُثّقت",ok:quality.duplicates===0||policies.removeDuplicates},{label:"القيم السالبة عولجت أو وُثّقت",ok:quality.negatives===0||policies.quarantineNegative},{label:"التوصية لا تدّعي سببًا",ok:true}], [analysis,cleanedRows.length,rawRows.length,quality,policies]);const passed=checks.filter(x=>x.ok).length;if(!rawRows.length)return <NeedData/>;return <div><StepHead eyebrow="07 · التحقق" title="النتيجة المقنعة ليست كافية" text="نعيد فحص الحساب، ونراجع أثر التنظيف، ونمنع الادعاءات التي لا يدعمها الملف."/><div className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="surface p-5"><div className="space-y-2">{checks.map((c,i)=><div className="verify-row" key={c.label}><span className={`verify-icon ${verified?(c.ok?"pass":"fail"):"pending"}`}>{verified?(c.ok?<CheckCircle2 className="h-5 w-5"/>:<AlertTriangle className="h-5 w-5"/>):i+1}</span><div><b>{c.label}</b><p>{verified?(c.ok?"اجتاز الفحص":"يحتاج مراجعة"):"بانتظار تشغيل الفحص"}</p></div></div>)}</div></div><div className="surface flex flex-col justify-between p-5"><div><ShieldCheck className="h-10 w-10 text-cyan-300"/><p className="mt-4 text-sm text-slate-500">نتيجة الفحص</p><div className="mt-1 text-5xl font-black">{verified?`${passed}/${checks.length}`:"—"}</div><Progress value={verified?passed/checks.length*100:0} className="mt-5 h-2 bg-white/7"/><p className="mt-4 text-sm leading-6 text-slate-500">الفحص يؤكد الاتساق الحسابي وحدود الادعاء، ولا يضمن جودة القرار خارج سياق العمل.</p></div><Button onClick={()=>setVerified(true)} className="mt-6 h-12 bg-cyan-300 font-black text-slate-950 hover:bg-cyan-200"><Play className="ml-2 h-4 w-4"/>تشغيل الفحص</Button></div></div><StepActions prev="/lab/dashboard" next="/lab/report" nextLabel="أنشئ تقرير القرار"/></div>}

